=== edaniele-tpi/playground/playground/schemas/airfoilsimulator.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/schemas/airfoilsimulator.schema.json",
  "title": "airfoilsimulator",
  "description": "A schema for the airfoilsimulator input",
  "$defs": {
    "conditions": {
      "description": "Operating conditions as list.",
      "type": "array",
      "uniqueItems": true,
      "default" : [{}],
      "items": { "$ref" : "https://example.com/schemas/condition.schema.json"}
    }
  },
  "type": "object",
  "oneOf" : [
    {"required": ["Original airfoil"]},
    {"required": ["Geometry"]}
  ],
  "properties": {
    "Case": { "$ref": "https://example.com/schemas/case.schema.json" },
    "Original airfoil": { 
      "$ref": "https://example.com/schemas/geometry.schema.json",
      "description" : "[Deprecated - Use `Geometry` instead] Geometry used for simulation.",
      "deprecated" : true
    },
    "Geometry" : { "$ref": "https://example.com/schemas/geometry.schema.json" },
    "Aerodynamic solver": { 
      "$ref": "https://example.com/schemas/solver.schema.json",
      "description" : "[Deprecated - Use `Solver` instead] Solver for aerodynamic simulation.",
      "deprecated" : true
    },
    "Solver" : { "$ref": "https://example.com/schemas/solver.schema.json" },
    "Operating conditions": { 
      "$ref": "#/$defs/conditions",
      "description" : "[Deprecated - Use `Conditions` instead] Operating conditions as list.",
      "deprecated" : true
    },
    "Conditions" : { "$ref": "#/$defs/conditions" },
    "Analysis" : { "$ref": "https://example.com/schemas/analysis.schema.json" }
  }
}

=== edaniele-tpi/playground/tests/configuration/input.json
{
  "Case": {
    "Name": "Preprocessed",
    "Description": "Case originated from companion oper matrix Excel /mnt/c/Users/e.daniele/Documents/__Aeroloads/Aerodynamics/Airfoils/99_ProfilAero/10_RnD/Airfoil_Development/20_airfoilsimulator/TPI40/cs/operMatrix_example.xlsx"
  },
  "Geometry": {
    "Filename": "airfoil"
  },
  "Solver": {
    "Type": "sfoil",
    "Grid" : {
      "engine" : "gmsh"
    }
  },
  "Conditions": [
    {
      "Reynolds": 600000.0,
      "Mach": 0.1,
      "Turbulence intensity": 0.106,
      "AoA-start": -5.0,
      "AoA-end": 25.0,
      "AoA-step": 0.5,
      "Boundary-Layer-Post": "true",
      "Transition": "Free",
      "Trailing-Edge-Serration": {
        "Length": 0.3,
        "Beta": 10.0
      }
    },
    {
      "Reynolds": 600000.0,
      "Mach": 0.1,
      "Turbulence intensity": 0.106,
      "AoA-start": -5.0,
      "AoA-end": 25.0,
      "AoA-step": 0.5,
      "Boundary-Layer-Post": "true",
      "Transition": [0.05, 0.10, "Zig-zag-tape", 0.03, 0.03],
      "Trailing-Edge-Serration": {
        "Length": 0.3,
        "Beta": 10.0
      }
    }
  ],
  "Analysis": {
    "Initialize?": "true",
    "Run?": "true",
    "Postprocess?": "true",
    "Plots?": "true",
    "Reports?": "true",
    "Extrapolation" : {
      "Type" : "Montgomerie-Lindenburg"
    },
    "Synthesis" : {
      "E-max" : {},
      "Lift-Slope" : {}
    }
  }
}

=== edaniele-tpi/playground/tests/configuration/input_validated.json
{
  "Case": {
    "Name": "Preprocessed",
    "Description": "Case originated from companion oper matrix Excel /mnt/c/Users/e.daniele/Documents/__Aeroloads/Aerodynamics/Airfoils/99_ProfilAero/10_RnD/Airfoil_Development/20_airfoilsimulator/TPI40/cs/operMatrix_example.xlsx"
  },
  "Geometry": {
    "Filename": "C:\\Users\\e.daniele\\Development\\GitHub\\playground\\tests\\configuration\\airfoil.dat",
    "Panel-number": 150
  },
  "Solver": {
    "Type": "sfoil",
    "Unsteady?": false,
    "TurbulenceModel": "SpalartAllmaras",
    "Grid": {
      "engine": "gmsh",
      "cgi": null,
      "Type": "o",
      "nx": 513,
      "ny": null,
      "nz": 1,
      "nte": null,
      "farfield": 30.0,
      "dz": 1.0
    }
  },
  "Conditions": [
    {
      "Reynolds": 600000.0,
      "Mach": 0.1,
      "Turbulence intensity": 0.106,
      "Transition": "Free",
      "G-beta locus": {
        "A": null,
        "B": null
      },
      "AoA-start": -5.0,
      "AoA-end": 25.0,
      "AoA-step": 0.5,
      "Vortex-Generator": null,
      "Trailing-Edge-Serration": {
        "Length": 0.3,
        "Beta": 10.0,
        "Width": 0.025
      },
      "Boundary-Layer-Post": true
    },
    {
      "Reynolds": 600000.0,
      "Mach": 0.1,
      "Turbulence intensity": 0.106,
      "Transition": [
        0.05,
        0.1,
        "Zig-zag-tape",
        0.03,
        0.03
      ],
      "G-beta locus": {
        "A": null,
        "B": null
      },
      "AoA-start": -5.0,
      "AoA-end": 25.0,
      "AoA-step": 0.5,
      "Vortex-Generator": null,
      "Trailing-Edge-Serration": {
        "Length": 0.3,
        "Beta": 10.0,
        "Width": 0.025
      },
      "Boundary-Layer-Post": true
    }
  ],
  "Analysis": {
    "Processors": 8,
    "Initialize?": true,
    "Run?": true,
    "Postprocess?": true,
    "Plots?": true,
    "Reports?": true,
    "Extrapolation": {
      "Type": "Montgomerie-Lindenburg",
      "CD3d-Correction": null,
      "Fix-Lift-Post-Stall": false,
      "Fix-Deep-Post-Stall-Range": false,
      "Fix-Lift-Post-Stall-Reverse-Flow": []
    },
    "Synthesis": {
      "E-max": {
        "Shift": [
          0.0
        ],
        "ShiftAsPercentage?": false
      },
      "Lift-Slope": {
        "Shift": [
          0.0
        ],
        "ShiftAsPercentage?": false
      }
    }
  }
}
